APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:2L9h2ale75ki/bKRfej6iEhGr+pLubkm9sutLQC+RNA=
APP_DEBUG=true
APP_URL=http://localhost

APP_LOCALE=en
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=en_US

APP_MAINTENANCE_DRIVER=file
# APP_MAINTENANCE_STORE=database

PHP_CLI_SERVER_WORKERS=4

BCRYPT_ROUNDS=12

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=ci4_crm
DB_USERNAME=root
DB_PASSWORD=

SESSION_DRIVER=redis
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null

BROADCAST_CONNECTION=reverb
BROADCAST_DRIVER=redis

FILESYSTEM_DISK=local
# QUEUE_CONNECTION=database
QUEUE_CONNECTION=redis
CACHE_STORE=database
# CACHE_PREFIX=



MEMCACHED_HOST=127.0.0.1

REDIS_CLIENT=phpredis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=log
MAIL_SCHEME=null
MAIL_HOST=127.0.0.1
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

VITE_APP_NAME="${APP_NAME}"

JWT_SECRET=MyS3cr3tK3y_F0rJwtT0k3n!


SANCTUM_STATEFUL_DOMAINS="http://localhost:8080"
SESSION_DOMAIN=".localhost:8080"



REVERB_APP_ID=579793
REVERB_APP_KEY=bkrrvw4ku22oz4b4fnsp
REVERB_APP_SECRET=be735dspjw8ketyfivzx
REVERB_HOST=127.0.0.1
REVERB_PORT=8080
REVERB_SCHEME=http

VITE_REVERB_APP_KEY="${REVERB_APP_KEY}"
VITE_REVERB_HOST="${REVERB_HOST}"
VITE_REVERB_PORT="${REVERB_PORT}"
VITE_REVERB_SCHEME="${REVERB_SCHEME}"

PUSHER_APP_ID=1896040
PUSHER_APP_KEY=470beb2b1e4f67d188fa
PUSHER_APP_SECRET=5570b540b182175c14d2
PUSHER_HOST=127.0.0.1
# PUSHER_HOST=192.168.68.64
PUSHER_PORT=6001
PUSHER_SCHEME=http
PUSHER_APP_CLUSTER=ap2

LARAVEL_ECHO_PORT=6001

REDIS_CLIENT=predis
CACHE_DRIVER=redis


TELESCOPE_ENABLED=true
TELESCOPE_DRIVER=database

REVERB_APP_ID=694754
REVERB_APP_KEY=sjf4kurlyvxiofvkbnnw
REVERB_APP_SECRET=wokihhdsgvt58ujmf9oj
REVERB_HOST="localhost"
REVERB_PORT=8080
REVERB_SCHEME=http

VITE_REVERB_APP_KEY="${REVERB_APP_KEY}"
VITE_REVERB_HOST="${REVERB_HOST}"
VITE_REVERB_PORT="${REVERB_PORT}"
VITE_REVERB_SCHEME="${REVERB_SCHEME}"
